### ISSUE TITLE
Grafana: Error when checking dashboard without login in

### ISSUE THREAD

**Issue by sanuim** [Software-Engineering-Jagiellonian/django-celery-frege#65]
When I opened Grafana page 'http://localhost:3000/' (dev) without logging in and opened 'All Collected Metrics' dashboard, I can see exclamation marks with error message: 'db query error: pq: password authentication failed for user "frege"'.

As a not logged in user, I should not see these errors, or if they are related to the display of the dashboard, then I should not have access to see it.

In this case, admin user should provide correct password in postgres settings and this fix the problem. Otherwise, this password should be set automatically.

![image](https://user-images.githubusercontent.com/55316324/212209424-7bc4abad-255c-4ebf-9279-f65267ad3abe.png)
![image](https://user-images.githubusercontent.com/55316324/212209382-39910173-cee7-4880-a463-3db2caa0ffc8.png)

**Comment by JaroslawHryszko** [comment]
This error can be easily removed by setting up proper password in Grafana's data sources.
